yarnPath: .yarn/releases/yarn-4.9.2.cjs

# 使用 node-modules 链接器而不是默认的 pnp
nodeLinker: node-modules

# 如果您需要使用特定的 npm registry，可以取消注释并修改下面这行
# npmRegistryServer: "https://registry.npmjs.org"

# 启用全局缓存以节省磁盘空间
enableGlobalCache: true

# 设置压缩格式以减少磁盘使用
compressionLevel: 0

# 在 CI 环境中启用更快的安装
enableScripts: false